### PR TITLE
providers missing compared to main repo

### PR DESCRIPTION
**Pull request by ksurl**
noticed these 3 were gone. some wildcard must have caught them when removing files? I was playing with the main repo and reorganizing there and noticed it had moved proxysh since i used mv *sh for the scripts in the root.

### CODE REVIEW

**Comment by haugene** [comment]
They only contain .sh scripts, I thought we'd let that be part of the main image. As they will be called from there.
That any provider that has an automated script is part of the running code and hence in the main repo, but the static files are here. Or do you think the scripts should live here as well? Pros/Cons?

**Comment by ksurl** [comment]
I can see both sides. If you download and extract static configs but leave automated ones in the main repo, you would not be able to use git since cloning requires an empty folder. We could separate further between automated providers and static config providers in separate folders? does the openvpn script already detect this? or does it check the contents of the provider folder to figure it out?

**Comment by haugene** [comment]
I was considering separating automated providers and static configs. Maintaining code is one thing, static files are another. There's also some inter-dependencies between the shell scripts. They are not executed, but sourced into the main script. This is to be aware of the environment variables. And to allow provider scripts to export environment variables and by doing that they can set configs in Transmission or other. FreeVPN has a config script that sets the OPENVPN_PASSWORD because it's grepped from a web page. Having this kind of flexibility is nice.

There is kind of a separation between the static and automated. It looks for a configure-openvpn.sh, and if it can't find it then it assumes it's a static file. Wouldn't be too hard to change the base path at that point and look in a static base folder for the actual configs. The whole sequence for locating the config file to use is not that long, have a look. It starts here: https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/start.sh#L36

**Comment by ksurl** [comment]
sounds good. I will close this PR. main repo can do a shallow git clone of the config repo to a static config only subfolder and the start script would need to update to look there.

**Pull request closed without merging**
